config/routes.rb
Rails.application.routes.draw do
  root "root#index"

  get "/dashboard", to: "dashboard/root#index"

  namespace :dashboard do
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'

    resources :articles do
      member do
        post :request_review
        post :approve
        post :publish
      end
    end

    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  enum status: {
    draft: 0,
    review: 1,
    scheduled: 2,
    published: 3,
  }

  has_rich_text :content

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  enum role: {
    writer: 0,
    moderator: 1,
  }

  validates :email, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  private

  def authenticate_user!
    redirect_to dashboard_login_path unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/dashboard/articles_controller.rb
module Dashboard
  class ArticlesController < ::DashboardController
    def index
      @articles = Article.all
    end

    def new
      @article = Article.new
    end

    def show
      @article = Article.find(params[:id])
    end

    def create
      @article = Article.new(article_params.merge(user: current_user))

      if @article.save
        redirect_to dashboard_article_path(@article)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to dashboard_article_path(@article)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy; end

    def request_review
      article = Article.find(params[:id])

      authorize(article)

      if article.draft? && article.review!
        redirect_to dashboard_article_path(article)
      end
    end

    def approve
      article = Article.find(params[:id])

      authorize(article)

      if article.review? && article.scheduled!
        redirect_to dashboard_article_path(article)
      end
    end

    def publish
      article = Article.find(params[:id])

      authorize(article)

      if article.update(status: :published, published_at: Time.current)
        redirect_to dashboard_article_path(article)
      end
    end

    private

    def article_params
      params.require(:article).permit(:title, :content, :scheduled_published_at, :published_at)
    end
  end
end

app/controllers/dashboard/root_controller.rb
module Dashboard
  class RootController < ::DashboardController
    def index
      redirect_to dashboard_articles_path
    end
  end
end

app/controllers/dashboard/sessions_controller.rb
module Dashboard
  class SessionsController < ::DashboardController
    skip_before_action :authenticate_user!, only: [:new, :create]

    layout "application"

    def new
      redirect_to dashboard_path if user_signed_in?
    end

    def create
      user = User.find_by(email: params[:user][:email])

      if user&.authenticate(params[:user][:password])
        login_user(user)
        redirect_to dashboard_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      logout
      redirect_to dashboard_login_path
    end

    private

    def login_user(user)
      session[:user_id] = user.id
    end

    def logout
      session.delete(:user_id)
    end
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < ::DashboardController
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def show
      @user = User.find(params[:id])
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to dashboard_user_path(@user)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.assign_attributes(user_params)

      authorize @user

      if @user.save
        redirect_to dashboard_user_path(@user)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy; end

    private

    def user_params
      params.require(:user).permit(:email, :role, :password)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  layout "dashboard"
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/articles/_form.html.erb
<%= form_with model: [:dashboard, article], class: "space-y-8" do |f| %>
  <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
    <div class="space-y-6 sm:space-y-5">
      <div>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">Article informations</p>
      </div>

      <div class="space-y-6 sm:space-y-5">
        <div
          class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
        >
          <%= f.label :title, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
            Title
          <% end %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <div class="flex max-w-lg rounded-md shadow-sm">
              <%=
                f.text_field :title,
                             class:
                               'block w-full min-w-0 flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm'
              %>
            </div>
          </div>
        </div>

        <div
          class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
        >
          <%= f.label :content, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
            Content
          <% end %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <%=
              f.rich_text_area :content,
                          class:
                            'block w-full max-w-lg rounded-md bg-white border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm'
            %>
          </div>
        </div>

        <div
          class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
        >
          <%= f.label :scheduled_published_at, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
            Scheduled publishing date
          <% end %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <div class="flex max-w-lg rounded-md shadow-sm">
              <%=
                f.datetime_field :scheduled_published_at,
                             class:
                               'block w-full min-w-0 flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm'
              %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pt-5 border-t border-t-gray-200">
    <div class="flex justify-end">
      <%= link_to "Back", dashboard_articles_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <button
        type="submit"
        class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
      >
        Submit
      </button>
    </div>
  </div>
<% end %>

app/views/dashboard/articles/edit.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">
        Update article
      </h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <%= render 'form', article: @article %>
    </div>
  </main>
</div>

app/views/dashboard/articles/index.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Articles</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <div class="px-4 sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center">
          <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">
              Articles
            </h1>
            <p class="mt-2 text-sm text-gray-700"></p>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            <%= link_to "Compose", new_dashboard_article_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
          </div>
        </div>
        <div class="mt-8 flex flex-col">
          <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div
              class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8"
            >
              <div
                class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg"
              >
                <table class="min-w-full divide-y divide-gray-300">
                  <thead class="bg-gray-50">
                    <tr>
                      <th
                        scope="col"
                        class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"
                      >
                        Title
                      </th>
                      <th
                        scope="col"
                        class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                      >
                        Status
                      </th>
                      <th
                        scope="col"
                        class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                      >
                        Scheduled publishing date
                      </th>
                      <th
                        scope="col"
                        class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                      >
                        Published date
                      </th>
                      <th
                        scope="col"
                        class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                      >
                        Author
                      </th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                        <span class="sr-only">View</span>
                      </th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                        <span class="sr-only">Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200 bg-white">
                    <% @articles.each do |article| %>
                      <tr>
                        <td
                          class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"
                        >
                          <%= article.title %>
                        </td>
                        <td
                          class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"
                        >
                          <%= article.status.capitalize %>
                        </td>
                        <td
                          class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"
                        >
                          <%= article.scheduled_published_at %>
                        </td>
                        <td
                          class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"
                        >
                          <%= article.published_at %>
                        </td>
                        <td
                          class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"
                        >
                          <%= article.user.email %>
                        </td>
                        <td
                          class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                        >
                          <%=
                            link_to 'View',
                                    dashboard_article_path(article),
                                    class:
                                      'text-indigo-600 hover:text-indigo-900'
                          %>
                        </td>
                        <td
                          class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                        >
                          <%=
                            link_to 'Edit',
                                    edit_dashboard_article_path(article),
                                    class:
                                      'text-indigo-600 hover:text-indigo-900'
                          %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/dashboard/articles/new.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Compose a new article</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <%= render 'form', article: @article %>
    </div>
  </main>
</div>

app/views/dashboard/articles/show.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">
        Article information
      </h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
          <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Title</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @article.title %>
              </dd>
            </div>
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Content</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @article.content %>
              </dd>
            </div>
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Status</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @article.status.capitalize %>
              </dd>
            </div>
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Scheduled publishing date</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @article.scheduled_published_at %>
              </dd>
            </div>
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Published at</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @article.published_at %>
              </dd>
            </div>
          </dl>
        </div>
      </div>
      <div class="pt-5 border-t border-t-gray-200">
        <div class="flex justify-end">
          <a class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" href="/dashboard/articles">Back</a>

          <% if policy(@article).request_review? %>
            <%= link_to "Request review", request_review_dashboard_article_path(@article), data: {turbo_method: :post}, class: "ml-3 rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          <% end %>

          <% if policy(@article).approve? %>
            <%= link_to "Approve", approve_dashboard_article_path(@article), data: {turbo_method: :post}, class: "ml-3 rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          <% end %>

          <% if policy(@article).publish? %>
            <%= link_to "Publish", publish_dashboard_article_path(@article), data: {turbo_method: :post}, class: "ml-3 rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/dashboard/users/_form.html.erb
<%= form_with model: [:dashboard, user], class: "space-y-8" do |f| %>
  <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
    <div class="space-y-6 sm:space-y-5">
      <div>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">User informations</p>
      </div>

      <div class="space-y-6 sm:space-y-5">
        <div
          class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
        >
          <%= f.label :email, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
            Email
          <% end %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <div class="flex max-w-lg rounded-md shadow-sm">
              <%=
                f.text_field :email,
                             class:
                               'block w-full min-w-0 flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm'
              %>
            </div>
          </div>
        </div>

        <% if f.object.new_record? %>
          <div
            class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
          >
            <%= f.label :password, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
              Password
            <% end %>
            <div class="mt-1 sm:col-span-2 sm:mt-0">
              <div class="flex max-w-lg rounded-md shadow-sm">
                <%=
                  f.password_field :password,
                               class:
                                 'block w-full min-w-0 flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm'
                %>
              </div>
            </div>
          </div>
        <% end %>

        <% if policy(f.object).update_role? %>
          <div
            class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5"
          >
            <%= f.label :role, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" do %>
              Status
            <% end %>
            <div class="mt-1 sm:col-span-2 sm:mt-0">
              <%=
                f.select :role,
                         User.roles.keys.map { |w| [w.capitalize, w] },
                         {},
                         {class:
                           'mt-1 block rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm'}
              %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="pt-5 border-t border-t-gray-200">
    <div class="flex justify-end">
      <%= link_to "Back", dashboard_users_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <button
        type="submit"
        class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
      >
        Submit
      </button>
    </div>
  </div>
<% end %>

app/views/dashboard/users/edit.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">
        Update user
      </h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <%= render 'form', user: @user %>
    </div>
  </main>
</div>

app/views/dashboard/users/index.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Users</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <div class="px-4 sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center">
          <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">
              Users
            </h1>
            <p class="mt-2 text-sm text-gray-700"></p>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            <%= link_to "Create", new_dashboard_user_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
          </div>
        </div>
        <div class="mt-8 flex flex-col">
          <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div
              class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8"
            >
              <div
                class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg"
              >
                <table class="min-w-full divide-y divide-gray-300">
                  <thead class="bg-gray-50">
                    <tr>
                      <th
                        scope="col"
                        class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"
                      >
                        Email
                      </th>
                      <th
                        scope="col"
                        class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                      >
                        Role
                      </th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                        <span class="sr-only">View</span>
                      </th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                        <span class="sr-only">Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200 bg-white">
                    <% @users.each do |user| %>
                      <tr>
                        <td
                          class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"
                        >
                          <%= user.email %>
                        </td>
                        <td
                          class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"
                        >
                          <%= user.role.capitalize %>
                        </td>
                        <td
                          class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                        >
                          <%=
                            link_to 'View',
                                    dashboard_user_path(user),
                                    class:
                                      'text-indigo-600 hover:text-indigo-900'
                          %>
                        </td>
                        <td
                          class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                        >
                          <%=
                            link_to 'Edit',
                                    edit_dashboard_user_path(user),
                                    class:
                                      'text-indigo-600 hover:text-indigo-900'
                          %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/dashboard/users/new.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Create a new user</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <%= render 'form', user: @user %>
    </div>
  </main>
</div>

app/views/dashboard/users/show.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">
        User information
      </h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
          <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Email</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @user.email %>
              </dd>
            </div>
            <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">Role</dt>
              <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                <%= @user.role %>
              </dd>
            </div>
          </dl>
        </div>
      </div>
      <div class="pt-5 border-t border-t-gray-200">
        <div class="flex justify-end">
          <a class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" href="/dashboard/users">Back</a>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ENewspaper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>ENewspaper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <%= render "layouts/dashboard_sidebar_menu" do %>
      <%= yield %>
    <% end %>
  </body>
</html>